#!/usr/bin/env python3
"""Compare Korean verb/adjective 4-form conjugations (-아/어, -(으)니, -는, -ㅂ/습니다)
generated by conjugate.py forms() against the KRDict JSON dump 활용형.

Compares only when the corresponding form exists in the dump:
  - eo: eoseo[:-1] compared against dump -아/어 forms (allowing vowel contractions like 가리키어=가리켜, 하여=해)
  - ni: nika[:-1] compared against dump -(으)니 forms
  - neun: mod_pres compared against dump -는 forms (verbs only)
  - formal: formal compared against dump present -ㅂ/습니다 forms (excluding past tense forms like 았/었습니다)

Entries without dump conjugation forms (196 items) are recorded as 'unverified'.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'scripts'))

from conjugate import forms, dec, comp


def expand_contraction(s):
    """Generate known Korean contracted/expanded equivalent forms."""
    forms_set = {s}
    if not s:
        return forms_set
    c, j, g = dec(s[-1])
    # 1. 하여 <-> 해
    if s.endswith('해'):
        forms_set.add(s[:-1] + '하여')
    if s.endswith('하여'):
        forms_set.add(s[:-2] + '해')
    # 2. ㅐ + 어 <-> ㅐ (보내어 <-> 보내, 힘내어 <-> 힘내)
    if j == 'ㅐ' and not g:
        forms_set.add(s + '어')
    if s.endswith('어') and len(s) >= 2 and dec(s[-2])[1] == 'ㅐ' and not dec(s[-2])[2]:
        forms_set.add(s[:-1])
    # 3. ㅔ + 어 <-> ㅔ (세어 <-> 세, 메어 <-> 메)
    if j == 'ㅔ' and not g:
        forms_set.add(s + '어')
    if s.endswith('어') and len(s) >= 2 and dec(s[-2])[1] == 'ㅔ' and not dec(s[-2])[2]:
        forms_set.add(s[:-1])
    # 4. ㅣ + 어 <-> ㅕ (가리키어 <-> 가리켜, 기다리어 <-> 기다려)
    if j == 'ㅕ' and not g:
        forms_set.add(s[:-1] + comp(c, 'ㅣ') + '어')
    if s.endswith('어') and len(s) >= 2 and dec(s[-2])[1] == 'ㅣ' and not dec(s[-2])[2]:
        c2 = dec(s[-2])[0]
        forms_set.add(s[:-2] + comp(c2, 'ㅕ'))
    # 5. ㅜ + 어 <-> ㅝ (바꾸어 <-> 바꿔, 나누어 <-> 나눠)
    if j == 'ㅝ' and not g:
        forms_set.add(s[:-1] + comp(c, 'ㅜ') + '어')
    if s.endswith('어') and len(s) >= 2 and dec(s[-2])[1] == 'ㅜ' and not dec(s[-2])[2]:
        c2 = dec(s[-2])[0]
        forms_set.add(s[:-2] + comp(c2, 'ㅝ'))
    # 6. ㅗ + 아 <-> ㅘ (바라보아 <-> 바라봐, 보아 <-> 봐)
    if j == 'ㅘ' and not g:
        forms_set.add(s[:-1] + comp(c, 'ㅗ') + '아')
    if s.endswith('아') and len(s) >= 2 and dec(s[-2])[1] == 'ㅗ' and not dec(s[-2])[2]:
        c2 = dec(s[-2])[0]
        forms_set.add(s[:-2] + comp(c2, 'ㅘ'))
    # 7. ㅚ + 어 <-> ㅙ (되어 <-> 돼)
    if j == 'ㅙ' and not g:
        forms_set.add(s[:-1] + comp(c, 'ㅚ') + '어')
    if s.endswith('어') and len(s) >= 2 and dec(s[-2])[1] == 'ㅚ' and not dec(s[-2])[2]:
        c2 = dec(s[-2])[0]
        forms_set.add(s[:-2] + comp(c2, 'ㅙ'))
    return forms_set


def eo_matches(gen_eo, dump_cands):
    """Check if generated -아/어 form matches any dump candidate, allowing contractions."""
    gen_variants = expand_contraction(gen_eo)
    for cand in dump_cands:
        cand_variants = expand_contraction(cand)
        if gen_variants & cand_variants:
            return True
    return False


def run_check(input_path=None, out_path=None):
    if input_path is None:
        input_path = ROOT / 'data/wip/verbs_krdict.json'
    else:
        input_path = Path(input_path)

    if out_path is None:
        out_path = ROOT / 'data/wip/conj_mismatch.json'
    else:
        out_path = Path(out_path)

    with open(input_path, 'r', encoding='utf-8') as f:
        entries = json.load(f)

    mismatches = []
    unverified = []

    for x in entries:
        conjs = [c.strip() for c in x.get('conj', []) if c and c.strip()]
        h = x.get('h')
        pos = x.get('pos')
        kid = str(x.get('id'))
        hom = str(x.get('homonym_number', '0'))

        if not conjs:
            unverified.append({
                'id': kid,
                'homonym_number': hom,
                'h': h,
                'pos': pos,
                'risk_note': '불규칙 위험 어간 (OVERRIDES null 후보)' if h == '뵙다' else None
            })
            continue

        f = forms(h, adj=(pos == '형용사'))
        gen_eo = f['eoseo'][:-1] if f.get('eoseo') else None
        gen_ni = f['nika'][:-1] if f.get('nika') else None
        gen_neun = f['mod_pres'] if pos == '동사' else None
        gen_formal = f.get('formal')

        diffs = {}

        # 1. ni: -(으)니
        dump_ni = [c for c in conjs if c.endswith('니')]
        if dump_ni and gen_ni not in dump_ni:
            diffs['ni'] = {'expected': dump_ni, 'gen': gen_ni}

        # 2. neun: -는 (동사만)
        if pos == '동사':
            dump_neun = [c for c in conjs if c.endswith('는')]
            if dump_neun and gen_neun not in dump_neun:
                diffs['neun'] = {'expected': dump_neun, 'gen': gen_neun}

        # 3. formal: 현재 격식형 -ㅂ/습니다 (과거형 았/었/였/했 제외)
        dump_formal = [
            c for c in conjs
            if (c.endswith('습니다') or c.endswith('ㅂ니다') or c.endswith('니다'))
            and not any(p in c for p in ['았', '었', '였', '했'])
        ]
        if dump_formal and gen_formal not in dump_formal:
            diffs['formal'] = {'expected': dump_formal, 'gen': gen_formal}

        # 4. eo: -아/어 (축약형 인정)
        dump_eo = [
            c for c in conjs
            if not (c.endswith('니') or c.endswith('는') or c.endswith('습니다') or c.endswith('ㅂ니다') or c.endswith('니다')
                    or c.endswith('고') or c.endswith('지') or dec(c[-1])[2] == 'ㄴ')
        ]
        if dump_eo and not eo_matches(gen_eo, dump_eo):
            diffs['eo'] = {'expected': dump_eo, 'gen': gen_eo}

        if diffs:
            mismatches.append({
                'id': kid,
                'homonym_number': hom,
                'h': h,
                'pos': pos,
                'diffs': diffs,
                'dump_conj': conjs,
            })

    result_data = {
        'mismatches': mismatches,
        'unverified': unverified,
        'stats': {
            'total': len(entries),
            'verified': len(entries) - len(unverified),
            'mismatches': len(mismatches),
            'unverified': len(unverified)
        }
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(result_data, ensure_ascii=False, indent=2), encoding='utf-8')

    print(f'Recorded {len(mismatches)} mismatches and {len(unverified)} unverified to {out_path}')
    print(f'실행 출력: 불일치 {len(mismatches)} / unverified {len(unverified)}')

    if mismatches:
        print('\n=== 불일치 목록 ===')
        for i, m in enumerate(mismatches, 1):
            diff_summary = [f"{k}: 생성({v['gen']}) vs 덤프({v['expected']})" for k, v in m['diffs'].items()]
            print(f"{i:2d}. {m['h']} ({m['pos']}): {', '.join(diff_summary)}")

    return mismatches, unverified


def main():
    parser = argparse.ArgumentParser(description='Check 4-form conjugations against krdict dump using conjugate.py forms().')
    parser.add_argument('--input', default=None, help='Path to verbs_krdict.json')
    parser.add_argument('--out', default=None, help='Output path for conj_mismatch.json')
    args = parser.parse_args()

    run_check(args.input, args.out)


if __name__ == '__main__':
    main()
